@extends('layout')
@section('content')<div class="heading"><h1>Hello, {{ auth()->user()->name }}</h1><p class="muted">Your wallet overview and recent activity.</p></div><div class="grid"><section><div class="card balance"><div class="row"><h2>Available balance</h2><span class="badge">PKR</span></div><div class="amount" id="balance-value">{{ number_format($wallet->balance_minor / 100, 2) }}</div><p class="muted">Customer #{{ auth()->id() }} · Personal wallet</p><button class="secondary" type="button" onclick="const e=document.getElementById('balance-value'); e.hidden=!e.hidden; this.textContent=e.hidden?'Show balance':'Hide balance';">Hide balance</button></div><div class="card"><h2>Account details</h2><p>{{ auth()->user()->email }}</p><a href="/wallets/{{ auth()->id() }}">View my wallet JSON →</a></div></section><section class="card"><h2>Send money</h2><p class="muted">Transfer to one of your saved beneficiaries.</p><form method="POST" action="/transfers">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><p><a href="/beneficiaries">Add / manage beneficiaries →</a></p>@if($customers->isEmpty())<p class="muted">Add your first beneficiary before sending money.</p>@endif<label for="receiver">Beneficiary</label><select id="receiver" name="receiver_id" required><option value="">Choose a beneficiary</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} — {{ $customer->email }}</option>@endforeach</select><label for="amount">Amount in PKR</label><input id="amount" name="amount" type="number" min="0.01" max="1000000" step="0.01" placeholder="2,000.00" required><p class="muted">Confirm the recipient and amount before sending.</p><button class="full">Transfer funds</button></form></section></div><section class="card">
<h2>Transfer history</h2><p class="muted">Latest 50 transfers</p>
<div class="table-wrap"><table><thead><tr>
<th>Date / UTC</th><th>Sender</th><th>Receiver</th><th>Amount / PKR</th><th>Status</th><th>Reference</th>
</tr></thead><tbody>
@forelse($transfers as $transfer)
<tr><td>{{ $transfer->created_at }}</td><td>{{ $transfer->sender_name }}</td>
<td>{{ $transfer->receiver_name }}</td><td>{{ number_format($transfer->amount_minor / 100, 2) }}</td>
<td>{{ ucfirst($transfer->status) }}</td><td style="overflow-wrap:anywhere">{{ $transfer->id }}</td></tr>
@empty<tr><td colspan="6">No transfers yet.</td></tr>@endforelse
</tbody></table></div></section>
<section class="card"><div class="row"><h2>Recent activity</h2><span class="muted">Latest 20 entries</span></div><div class="table-wrap"><table><thead><tr><th>Date / UTC</th><th>Description</th><th>Reference</th><th>Amount / PKR</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->created_at }}</td><td>{{ $entry->description }}</td><td>{{ $entry->transfer_id ? substr($entry->transfer_id,0,8) : ($entry->payment_event_id ? 'PAY-'.$entry->payment_event_id : 'OPENING') }}</td><td class="{{ $entry->amount_minor >= 0 ? 'credit' : 'debit' }}">{{ $entry->amount_minor >= 0 ? '+' : '' }}{{ number_format($entry->amount_minor/100,2) }}</td></tr>@empty<tr><td colspan="4">No transactions yet.</td></tr>@endforelse</tbody></table></div></section>@endsection
