<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Fintech Wallet Lab</title>
<style>
:root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#172536;background:#f4f6fa}*{box-sizing:border-box}body{margin:0}header{background:#112c3c;color:white;padding:22px 6%;display:flex;align-items:center;justify-content:space-between;gap:16px}header strong{font-size:22px;letter-spacing:-.5px}a{color:#137566}header a{color:white}main{max-width:1120px;margin:32px auto;padding:0 22px}.badge{display:inline-block;padding:6px 10px;border-radius:20px;font-size:12px;font-weight:700;letter-spacing:.7px;background:#dcf5eb;color:#166750}.danger{background:#ffe1db;color:#9c3020}.banner{font-size:13px;padding:12px 6%;background:#e7eef3;color:#425969}.grid{display:grid;grid-template-columns:1fr 1.2fr;gap:24px}.card{background:white;border:1px solid #e1e7ee;border-radius:16px;padding:26px;margin-bottom:24px;box-shadow:0 4px 16px #132b4210}.balance{background:#153f48;color:white;border:0}.balance h2{font-weight:400;font-size:15px;color:#c1dbdf}.amount{font-size:42px;font-weight:650;letter-spacing:-1.5px;margin:20px 0}.muted{font-size:14px;color:#657586}.balance .muted{color:#bbd5d8}h1{font-size:28px;margin-bottom:6px}h2{font-size:19px;margin-top:0}label{display:block;font-size:14px;font-weight:600;margin:18px 0 8px}input,select{width:100%;border:1px solid #cfd8e2;padding:12px;border-radius:8px;font:inherit;background:white}button,.button{background:#137566;color:white;border:0;border-radius:8px;padding:12px 18px;font:inherit;font-weight:600;cursor:pointer;text-decoration:none;display:inline-block}button.secondary{background:#e8f1f0;color:#155c52}.full{width:100%;margin-top:22px}.alert{padding:15px;border-radius:9px;background:#e1f3e9;color:#185c40;margin-bottom:20px;overflow-wrap:anywhere}.error{background:#ffeae6;color:#9c3020}.auth{max-width:440px;margin:50px auto}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:16px 12px;border-bottom:1px solid #e7ecf2;white-space:nowrap}th{color:#667587;font-size:12px;text-transform:uppercase}.credit{color:#087652;font-weight:650}.debit{color:#a23e37;font-weight:650}footer{font-size:12px;color:#6f7c8c;text-align:center;padding:20px}code{font-size:12px}form.inline{display:inline}.heading{margin-bottom:26px}.row{display:flex;justify-content:space-between;align-items:center;gap:10px}@media(max-width:760px){.grid{grid-template-columns:1fr}header{flex-wrap:wrap}.amount{font-size:34px}}
</style></head><body><header><strong>◈ Fintech <span style="font-weight:400">Wallet Lab</span></strong><div class="row"><span class="badge {{ config('lab.vulnerable') ? 'danger' : '' }}">{{ config('lab.vulnerable') ? 'VULNERABLE DEMO' : 'SECURED DEMO' }}</span>@auth<form class="inline" method="POST" action="/logout">@csrf<button class="secondary">Log out</button></form>@endauth</div></header>
<div class="banner">Secure System Design assessment · Local teaching environment · Synthetic funds only</div>
<main>@if(session('success'))<div class="alert" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error" role="alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@yield('content')</main><footer>PKR amounts are stored as integer paisa. This application is an assessment laboratory.</footer></body></html>
